# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'ShareExtensionsSample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  
  # Pods for ShareExtensionsSample

  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD', '~> 1.0.0'


  target 'ShareExtensionsSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ShareExtensions' do
    pod 'AFNetworking', '~> 3.0'
    pod 'MBProgressHUD', '~> 1.0.0'
end




